# Generated by Django 4.2 on 2023-05-07 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfdiscovery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
    ]
